# Generated by Django 3.0.7 on 2021-02-23 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_mutualfund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mutualfund',
        ),
    ]
