# Generated by Django 3.0.7 on 2021-02-23 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_mutualfund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfund',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutualfunds', to='portfolio.Customer'),
        ),
    ]
